### ISSUE TITLE
json string error:it would add '\' in the json string when reading data.

### ISSUE THREAD

**Issue by ElderJames** [pootzko/InfluxData.Net#58] opened 2017-09-24 10:46 UTC
There is the json string in database:

```
 {"Name":"go\ to\ work"\,"Desception":"fighting!"\,"FinishTime":"2017-09-25T17:36:44.6631897+08:00"\,"AggregateId":"1ba4d283-4cd4-48ad-b04b-6c68bdeac784"\,"Version":2\,"Timestamp":"2017-09-24T17:36:45.173955+08:00"\,"EventType":"Shriek.Samples.Events.TodoChangedEvent"}
```

😢 what's wrong?

**Comment by pootzko** [comment] 2017-09-24 11:35
Hi,

thanks for reporting this, but you'll need to provide more details for me to be able to reproduce the issue you're having. From that short JSON snippet, it's not clear at all how to reproduce the issue. Please provide enough details to reproduce this such as - a sample of data that's going into your influxdb, what output are you expecting once you query influxdb, what you're getting instead etc.. Thnx

**Comment by ElderJames** [comment] 2017-09-24 12:47
The origin data is 
```json
{"Name":"call boss","Desception":"haha!","FinishTime":"2017-09-25T20:41:23.490838+08:00","Id":0,"AggregateId":"21262941-ba0b-4337-ad34-5c4b31b470ab","Version":2,"EventVersion":2,"CanCommit":true}
```
And I set this parameter to Point.Fields ,then call the `WriteAsync` Method.

The data would change to wrong json in database because the char '/'.

**Comment by ElderJames** [comment] 2017-09-25 05:58
I know it must add "\\" to  escape some character. But when the client read data from database, it must remove these character.
Now I must use `Replace("\\","")` to remove them.

**Comment by pootzko** [comment] 2017-09-29 21:17
Hey man, thanks a lot for the PR. I'll try to test it out over the weekend and then deploy it to nuget. Cheers!

**Comment by pootzko** [comment] 2017-10-01 17:59
A quick question for you for when you have the time to reply. I'm just trying to reproduce your issue before your fix and I want to create a few tests for it so I don't introduce a breaking change into the lib for all the people who are already using it in production (it's a DB adapter library after all, so I have to be careful).

The JSON that you provided:

```json
{"Name":"go to work","Desception":"fighting!","FinishTime":"2017-09-25T20:47:23.8341218+08:00","AggregateId":"213b1306-a4f3-44a3-9a4b-609cef63517f","Version":2,"Timestamp":"2017-09-24T20:47:24.6943984+08:00","EventType":"Shriek.Samples.Events.TodoChangedEvent"}
```

That's all part of a single InfluxDB field am I correct? Or did you map each JSON property from your JSON to a separate InfluxDB field? Thnx!

**Comment by pootzko** [comment] 2017-10-01 19:16
Also, I believe this is related to #49. I'll work on that first so this kind of fix might not be even necessary.

**Comment by MartinGroh** [comment] 2017-10-03 10:59
Hey, I seem to have the same problem. I save a Field of DateTime that I serialized as string (datetime.ToString()) and when I read I back form influx I get a \ in the space between the date and the time. (03.10.2017\ 12.09.52)

I haven’t looked into what’s being sent yet, but it seems to be the same effect as if one is to escape the whitespace inside an “quoted string “.

Regards Martin

**Comment by pootzko** [comment] 2017-10-03 11:04
Yup, I've been working on the library for the past few days, so I expect this to be resolved and deployed within the next few days. Will let you know once it's live. Cheers

**Comment by pootzko** [comment] 2017-10-04 22:41
Hi guys,

I updated the formatter to match the [docs](https://docs.influxdata.com/influxdb/v1.3/write_protocols/line_protocol_reference/#special-characters). Not deployed to nuget yet because I have a few more things to update in the library before that. If you need this asap, feel free to use the dev branch. I'll close this task and if you want to continue the discussion, please continue on #49.

**Closed by pootzko** 2017-10-04 22:41 UTC
